/* ============================================================
   STREETSTORE — Translations  (EN / FR / AR)
   ============================================================ */
const TRANSLATIONS = {
  en: {
    // Nav
    nav_shop:"Shop", nav_lookbook:"Lookbook", nav_about:"About",
    nav_contact:"Contact", nav_account:"Account",
    // Hero
    hero_tag:"New Collection — Spring 2026",
    hero_h1_1:"TIMELESS DENIM.", hero_h1_2:"MODERN FIT.",
    hero_sub:"Premium Moroccan denim fashion. Crafted for bold, modern women.",
    hero_shop:"Shop Now", hero_lookbook:"View Lookbook",
    // Benefits
    benefit_quality:"Best Quality Fabrics", benefit_quality_sub:"Durable, comfy, perfect for daily wear",
    benefit_delivery:"Fast Delivery",       benefit_delivery_sub:"Get your favorite jeans delivered quickly",
    benefit_price:"Affordable Prices",      benefit_price_sub:"Fashion that fits your budget",
    // Grid
    new_in:"New In", the_collection:"The Collection", view_all:"View All →",
    quick_add:"Quick Add", sale:"Sale", trending:"Trending",
    // Trending section
    trending_now:"Trending Now", trending_sub:"The looks everyone's talking about this season.", shop_trending:"Shop Trending",
    // Editorial
    editorial:"Editorial", dress_street:"Dress the Street.",
    // Instagram
    the_feed:"The Feed", follow_insta:"Follow on Instagram",
    // Newsletter
    newsletter_label:"Newsletter", be_first:"Be First to Know",
    newsletter_sub:"New drops, exclusive offers, and behind-the-scenes — straight to your inbox.",
    subscribe:"Subscribe", email_placeholder:"Your email address",
    // Product page
    product_color:"Color:", product_size:"Size:", select_size:"Select a size",
    product_qty:"Quantity", add_to_cart:"Add to Cart",
    add_to_wishlist:"♡ Add to Wishlist", size_guide:"Size Guide",
    free_shipping:"Free Shipping", easy_returns:"Easy Returns", secure_payment:"Secure Payment",
    product_details:"Product Details", fabric_care:"Fabric & Care",
    acc_shipping_returns:"Shipping & Returns",
    complete_look:"Complete the Look",
    customer_reviews:"Customer Reviews", reviews_count:"Based on 48 reviews",
    skip:"Skip ›", zoom_hint:"⊕ Zoom", sold_out_badge:"Sold Out",
    reviews_avg_label:"Based on 48 reviews",
    // Shop
    all_jeans:"All Jeans", filters:"Filters", clear_all:"Clear All", no_results:"No products match your filters.",
    sort_by:"Sort By", sort_featured:"Featured",
    sort_price_asc:"Price: Low to High", sort_price_desc:"Price: High to Low", sort_newest:"Newest",
    filter_size:"Size", filter_color:"Color", filter_fit:"Fit", filter_price:"Price",
    fit_all:"All", fit_skinny:"Skinny", fit_wide:"Wide Leg", fit_straight:"Straight", fit_mom:"Mom",
    // Cart
    your_cart:"Your Cart", subtotal:"Subtotal",
    free_ship_note:"Free shipping on all orders",
    checkout_btn:"Checkout", continue_shopping:"Continue Shopping →",
    cart_empty:"Your cart is empty.", you_might_like:"You might also like",
    shop_now_btn:"Shop Now",
    // Checkout
    step_info:"Information", step_shipping:"Shipping", step_payment:"Payment",
    contact_info:"Contact Information", shipping_method:"Shipping Method", payment:"Payment",
    first_name:"First Name", last_name:"Last Name", email:"Email",
    address_label:"Address", city:"City", postal_code:"Postal Code", country:"Country",
    continue_to_shipping:"Continue to Shipping", continue_to_payment:"Continue to Payment",
    place_order:"Place Order →", back_btn:"← Back", return_to_cart:"← Return to cart",
    standard_shipping:"Standard Shipping", express_shipping:"Express Shipping",
    days_std:"5–7 business days", days_exp:"2–3 business days",
    cod_title:"Cash on Delivery",
    cod_desc:"You will pay in cash when your order arrives at your door. No card required.",
    cod_note1:"📦 Our delivery agent will contact you before arrival.",
    cod_note2:"✅ Please have the exact amount ready.",
    cod_note3:"🔒 Your order is 100% secure and guaranteed.",
    cod_note4:"🇲🇦 We deliver across Morocco.",
    order_summary:"Order Summary", shipping_label:"Shipping", total_label:"Total", free:"Free",
    promo_code:"Promo Code", apply:"Apply", promo_ph:"Enter code",
    // About
    our_story:"Our Story", born_street:"Born on the street. Built for you.",
    explore_collection:"Explore the Collection",
    what_we_stand:"What We Stand For", our_values:"Our Values",
    meet_team:"Meet the Team", browse_all:"Browse All Jeans",
    shop_collection_cta:"Shop the Collection",
    stat_styles:"Styles", stat_quality:"Quality", stat_payment:"Payment", stat_shipping_label:"Shipping",
    about_manifesto_label:"Our Manifesto",
    // Lookbook
    lookbook_subtitle:"Spring / Summer 2026",
    shop_the_look:"Shop the Look", ready_to_shop:"Ready to Shop?",
    lookbook_ready_sub:"Explore the full collection and find your perfect fit.",
    shop_all_jeans:"Shop All Jeans",
    // Contact
    reach_out:"Reach Out", get_in_touch:"Get in Touch",
    send_message_title:"Send a Message",
    subject_label:"Subject", message_label:"Message", send_message:"Send Message",
    message_ph:"Tell us how we can help...", select_topic:"Select a topic",
    topic_order:"Order Inquiry", topic_returns:"Returns & Exchanges",
    topic_size:"Size & Fit Help", topic_wholesale:"Wholesale & Collaboration",
    topic_press:"Press & Media", topic_other:"Other",
    find_us:"Find Us Online", we_respond:"We respond within 24 hours",
    based_morocco:"Based in Morocco — We deliver across Morocco",
    // Account
    my_orders:"My Orders", wishlist:"Wishlist", profile:"Profile",
    addresses_tab:"Addresses", logout:"Logout", member_since:"Member since 2024",
    track:"Track", reorder:"Reorder",
    status_processing:"Processing", status_shipped:"Shipped", status_delivered:"Delivered",
    order_num:"Order #", date_col:"Date", items_col:"Items",
    total_col:"Total", status_col:"Status", action_col:"Action",
    // Footer
    footer_desc:"Premium women's denim crafted for the streets and everywhere in between.",
    footer_shop:"Shop", footer_help:"Help", footer_follow:"Follow",
    footer_all_jeans:"All Jeans", footer_new:"New Arrivals", footer_sale:"Sale",
    footer_contact:"Contact Us", footer_size_guide:"Size Guide",
    footer_shipping:"Shipping & Returns", footer_faq:"FAQ",
    footer_account:"My Account", footer_track:"Track Order",
    footer_rights:"© 2026 StreetStore. All rights reserved.",
    privacy:"Privacy Policy", terms:"Terms", cookies:"Cookie Policy",
    // Breadcrumb
    home:"Home",
    // Thank you
    order_confirmed:"Order Confirmed!",
    track_order:"Track Your Order", continue_shopping_btn:"Continue Shopping",
    order_confirmed_sub:"Your order has been placed successfully. Our team will contact you before delivery.",
    order_est_delivery:"Estimated delivery: 3–5 business days",
    shipping_info:"Shipping Info",
    // Checkout extras
    phone_label:"Phone Number",
    phone_error:"Please enter at least 10 digits.",
    upsell_title:"Take advantage of the duo deal!",
    upsell_desc:"Add a 2nd jean and save 39 MAD on your order.",
    upsell_cta:"Add →",
    deal_applied_pre:"Duo deal applied — you save",
    deal_applied_suf:"!",
    discount_label:"Duo deal discount",
    limited_offer:"🎁 Limited Offer",
    pack_deal_line1:"2 items → 319 MAD · 3 items → 479 MAD",
    pack_deal_line2:"Mix & match any styles — discount applied automatically in cart",
    pack_save:"Save up to 10% off",
    based_on_reviews:"Based on 48 reviews",
    // Contact
    contact_hero_tag:"✦ We're Here to Help",
    contact_hero_title:"Let's Talk",
    contact_hero_sub:"Have a question about your order, sizing, or just want to say hello? We'd love to hear from you.",
    stat_response:"Response Time", stat_channels:"Contact Channels", stat_cod_label:"Cash on Delivery",
    reach_channels:"Reach out",
    channels_sub:"We're available on WhatsApp, Instagram, and Facebook. Pick whichever feels most comfortable for you.",
    channel_wa_sub:"Chat with us directly",
    channel_ig_sub:"DM us on Instagram",
    channel_fb_sub:"Send us a message",
    channel_response:"We typically respond within 24 hours",
    form_sub:"Fill in the form and we'll get back to you as soon as possible.",
    first_name_label:"First Name", last_name_label:"Last Name", email_label:"Email Address",
    topic_label:"Topic", topic_placeholder:"Select a topic…",
    form_disclaimer:"We'll reply within 24 hours. No spam, ever.",
    find_online:"Find Us Online",
    prefer_chat:"Prefer to Chat?",
    prefer_chat_sub:"WhatsApp is the fastest way to reach us. Send us a message and we'll help you find the perfect pair.",
    chat_whatsapp:"Chat on WhatsApp",
    browse_collection:"Browse Collection →",
    msg_sent:"Message Sent!",
    msg_sent_sub:"Thanks for reaching out. We'll get back to you within 24 hours.",
    // FAQ
    faq_hero_tag:"✦ Help Center",
    faq_hero_title:"Got a question? We've got answers.",
    faq_hero_sub:"Find answers to the most common questions about orders, sizing, shipping, and more.",
    faq_search_ph:"Search questions…",
    faq_no_results:"No results found. Try a different keyword or contact us.",
    faq_cat_all:"All Questions", faq_cat_orders:"Orders & Payment",
    faq_cat_shipping:"Shipping", faq_cat_sizing:"Sizing & Fit", faq_cat_exchanges:"Exchanges",
    still_help:"Still need help?",
    still_help_sub:"Can't find your answer? Our team responds within 24 hours — reach us directly.",
    contact_us_arrow:"Contact Us →",
    // Lookbook
    lookbook_series1:"Urban Series", lookbook_series2:"Dark Edit",
    lookbook_series3:"Sky Wash", lookbook_grey:"The Grey Scale",
    // About
    about_hero_sub:"WE ARE STREETSTORE",
    about_story_p:"StreetStore was born from a passion for premium denim fashion. Based in Morocco, we bring you the latest in women's denim — from wide-leg classics to modern baggy fits — at prices that make sense. Every piece is carefully selected for quality, comfort, and style.",
    val1_title:"Premium Quality", val1_desc:"We use only the finest denim fabrics, sourced from certified mills. Each pair goes through 40+ quality checks before it reaches you.",
    val2_title:"Sustainable", val2_desc:"Our production process uses 50% less water than industry standard. Packaging is fully recyclable. We offset 100% of our carbon emissions.",
    val3_title:"Inclusive Sizing", val3_desc:"Great denim is for every body. We offer sizes XS through XXL and continuously expand our range based on real customer feedback.",
    team_title:"Meet the Team", team_section:"The People",
    role1:"Founder & Creative Director", role2:"Head of Design", role3:"Head of Sustainability",
    cta_sub:"Premium denim for the modern woman. Explore 12 signature styles, crafted to last.",
    // Contact stat
    stat_based:"Based in Morocco",
    // FAQ stats & extra
    faq_stat_questions:"Questions answered", faq_stat_categories:"Categories",
    still_here:"We're always here.",
    faq_grp_shipping:"Shipping & Delivery", faq_grp_exchanges:"Exchanges & Policy",
    // About
    about_est:"Est. — Morocco",
    // Lookbook
    lookbook_title:"THE LOOKBOOK",
    // Shipping page
    sp_eyebrow:"✦ Our Policies",
    sp_hero_sub:"Clear, simple, and honest — everything you need to know before and after your order.",
    sp_stat1_val:"Free", sp_stat1_label:"Shipping",
    sp_stat2_label:"Exchange window", sp_stat3_label:"Exchange fee",
    sp_important:"Important — Please Read Before Ordering",
    sp_final_sale:"Final Sale",
    sp_pill1:"✗ No refunds", sp_pill2:"✗ No returns", sp_pill3:"✓ Size exchange only",
    sp_card1_label:"Standard Delivery", sp_card1_val:"Free",
    sp_card1_note:"All orders across Morocco. Delivered within 2–5 business days.",
    sp_card2_label:"Express Delivery",
    sp_card2_note:"Priority dispatch. Delivered within 1–2 business days.",
    sp_card3_label:"Order Processing",
    sp_card3_note:"Orders before 3 PM are processed the same day.",
    sp_fee_tag:"Exchange Fee", sp_fee_h3:"Re-shipping fee applies",
    sp_step1_h4:"Contact us",
    sp_step1_p:"Message us on WhatsApp or via the contact form within 3 business days of delivery.",
    sp_step2_h4:"Send a photo",
    sp_step2_p:"Photo of the item — unworn, tags attached — so we can confirm eligibility.",
    sp_step3_h4:"Pay the 35 MAD",
    sp_step3_p:"Pay the exchange fee. Your new size is dispatched immediately after confirmation.",
    sp_step4_h4:"Hand back the item",
    sp_step4_p:"Give the original item to our delivery agent when they arrive with your new size.",
    sp_cta_eyebrow:"We're here for you", sp_cta_h3:"Still have questions?",
    sp_cta_p:"Reach our team on WhatsApp or through the contact page — we respond fast.",
    sp_cta_wa:"Chat on WhatsApp", sp_cta_contact:"Contact Us →",
    sp_breadcrumb:"Shipping & Exchanges",
  },

  fr: {
    nav_shop:"Boutique", nav_lookbook:"Lookbook", nav_about:"À propos",
    nav_contact:"Contact", nav_account:"Compte",
    hero_tag:"Nouvelle Collection — Printemps 2026",
    hero_h1_1:"DENIM INTEMPOREL.", hero_h1_2:"COUPE MODERNE.",
    hero_sub:"Mode denim marocaine premium. Conçue pour les femmes audacieuses et modernes.",
    hero_shop:"Acheter maintenant", hero_lookbook:"Voir le Lookbook",
    benefit_quality:"Meilleure Qualité", benefit_quality_sub:"Durable, confortable, parfait pour le quotidien",
    benefit_delivery:"Livraison Rapide",  benefit_delivery_sub:"Recevez votre jean préféré rapidement",
    benefit_price:"Prix Abordables",     benefit_price_sub:"La mode qui s'adapte à votre budget",
    new_in:"Nouveautés", the_collection:"La Collection", view_all:"Voir tout →",
    quick_add:"Ajouter", sale:"Soldes", trending:"Tendance",
    trending_now:"Tendance du moment", trending_sub:"Les looks dont tout le monde parle cette saison.", shop_trending:"Voir les tendances",
    editorial:"Éditorial", dress_street:"Habille la rue.",
    the_feed:"Notre feed", follow_insta:"Suivre sur Instagram",
    newsletter_label:"Newsletter", be_first:"Soyez la première informée",
    newsletter_sub:"Nouvelles collections, offres exclusives, et coulisses — dans votre boîte mail.",
    subscribe:"S'abonner", email_placeholder:"Votre adresse e-mail",
    product_color:"Couleur:", product_size:"Taille:", select_size:"Choisir une taille",
    product_qty:"Quantité", add_to_cart:"Ajouter au panier",
    add_to_wishlist:"♡ Ajouter aux favoris", size_guide:"Guide des tailles",
    free_shipping:"Livraison gratuite", easy_returns:"Retours faciles", secure_payment:"Paiement sécurisé",
    product_details:"Détails du produit", fabric_care:"Tissu & Entretien",
    acc_shipping_returns:"Livraison & Retours",
    complete_look:"Complétez le look",
    customer_reviews:"Avis clients", reviews_count:"Basé sur 48 avis",
    skip:"Passer ›", zoom_hint:"⊕ Zoom", sold_out_badge:"Épuisé",
    reviews_avg_label:"Basé sur 48 avis",
    all_jeans:"Tous les jeans", filters:"Filtres", clear_all:"Effacer tout", no_results:"Aucun produit ne correspond à vos filtres.",
    sort_by:"Trier par", sort_featured:"En vedette",
    sort_price_asc:"Prix croissant", sort_price_desc:"Prix décroissant", sort_newest:"Nouveautés",
    filter_size:"Taille", filter_color:"Couleur", filter_fit:"Coupe", filter_price:"Prix",
    fit_all:"Tout", fit_skinny:"Skinny", fit_wide:"Jambe large", fit_straight:"Droit", fit_mom:"Mom",
    your_cart:"Votre Panier", subtotal:"Sous-total",
    free_ship_note:"Livraison gratuite sur toutes les commandes",
    checkout_btn:"Commander", continue_shopping:"Continuer vos achats →",
    cart_empty:"Votre panier est vide.", you_might_like:"Vous aimerez aussi",
    shop_now_btn:"Acheter maintenant",
    step_info:"Information", step_shipping:"Livraison", step_payment:"Paiement",
    contact_info:"Informations de contact", shipping_method:"Mode de livraison", payment:"Paiement",
    first_name:"Prénom", last_name:"Nom", email:"E-mail",
    address_label:"Adresse", city:"Ville", postal_code:"Code postal", country:"Pays",
    continue_to_shipping:"Continuer vers la livraison", continue_to_payment:"Continuer vers le paiement",
    place_order:"Passer la commande →", back_btn:"← Retour", return_to_cart:"← Retour au panier",
    standard_shipping:"Livraison standard", express_shipping:"Livraison express",
    days_std:"5–7 jours ouvrables", days_exp:"2–3 jours ouvrables",
    cod_title:"Paiement à la livraison",
    cod_desc:"Vous payez en espèces à la réception de votre colis. Aucune carte requise.",
    cod_note1:"📦 Notre livreur vous contactera avant l'arrivée.",
    cod_note2:"✅ Veuillez avoir le montant exact.",
    cod_note3:"🔒 Votre commande est 100% sécurisée.",
    cod_note4:"🇲🇦 Nous livrons partout au Maroc.",
    order_summary:"Récapitulatif", shipping_label:"Livraison", total_label:"Total", free:"Gratuit",
    promo_code:"Code promo", apply:"Appliquer", promo_ph:"Entrer le code",
    our_story:"Notre Histoire", born_street:"Né dans la rue. Fait pour vous.",
    explore_collection:"Explorer la collection",
    what_we_stand:"Ce que nous défendons", our_values:"Nos Valeurs",
    meet_team:"Rencontrez l'équipe", browse_all:"Voir tous les jeans",
    shop_collection_cta:"Découvrir la Collection",
    stat_styles:"Styles", stat_quality:"Qualité", stat_payment:"Paiement", stat_shipping_label:"Livraison",
    about_manifesto_label:"Notre Manifeste",
    lookbook_subtitle:"Printemps / Été 2026",
    shop_the_look:"Acheter le look", ready_to_shop:"Prête à faire du shopping?",
    lookbook_ready_sub:"Explorez la collection complète et trouvez votre style parfait.",
    shop_all_jeans:"Voir tous les jeans",
    reach_out:"Contactez-nous", get_in_touch:"Prendre contact",
    send_message_title:"Envoyer un message",
    subject_label:"Sujet", message_label:"Message", send_message:"Envoyer",
    message_ph:"Comment pouvons-nous vous aider...", select_topic:"Sélectionner un sujet",
    topic_order:"Renseignement sur commande", topic_returns:"Retours & Échanges",
    topic_size:"Aide taille & coupe", topic_wholesale:"Vente en gros & Collaboration",
    topic_press:"Presse & Médias", topic_other:"Autre",
    find_us:"Retrouvez-nous en ligne", we_respond:"Nous répondons sous 24h",
    based_morocco:"Basé au Maroc — Nous livrons partout au Maroc",
    my_orders:"Mes commandes", wishlist:"Favoris", profile:"Profil",
    addresses_tab:"Adresses", logout:"Déconnexion", member_since:"Membre depuis 2024",
    track:"Suivre", reorder:"Recommander",
    status_processing:"En traitement", status_shipped:"Expédié", status_delivered:"Livré",
    order_num:"Commande #", date_col:"Date", items_col:"Articles",
    total_col:"Total", status_col:"Statut", action_col:"Action",
    footer_desc:"Denim féminin premium, conçu pour les rues et bien plus encore.",
    footer_shop:"Boutique", footer_help:"Aide", footer_follow:"Suivre",
    footer_all_jeans:"Tous les jeans", footer_new:"Nouveautés", footer_sale:"Soldes",
    footer_contact:"Nous contacter", footer_size_guide:"Guide des tailles",
    footer_shipping:"Livraison & Retours", footer_faq:"FAQ",
    footer_account:"Mon compte", footer_track:"Suivre ma commande",
    footer_rights:"© 2026 StreetStore. Tous droits réservés.",
    privacy:"Politique de confidentialité", terms:"Conditions", cookies:"Politique cookies",
    home:"Accueil",
    order_confirmed:"Commande confirmée!",
    track_order:"Suivre ma commande", continue_shopping_btn:"Continuer mes achats",
    order_confirmed_sub:"Votre commande a été passée avec succès. Notre équipe vous contactera avant la livraison.",
    order_est_delivery:"Livraison estimée : 3–5 jours ouvrables",
    shipping_info:"Infos de livraison",
    // Checkout extras
    phone_label:"Numéro de téléphone",
    phone_error:"Le numéro doit contenir au moins 10 chiffres.",
    upsell_title:"Profitez de l'offre duo !",
    upsell_desc:"Ajoutez un 2ème jean et économisez 39 MAD sur votre commande.",
    upsell_cta:"Ajouter →",
    deal_applied_pre:"Offre duo appliquée — vous économisez",
    deal_applied_suf:"!",
    discount_label:"Réduction offre duo",
    limited_offer:"🎁 Offre Limitée",
    pack_deal_line1:"2 articles → 319 MAD · 3 articles → 479 MAD",
    pack_deal_line2:"Mixez les styles — la réduction s'applique automatiquement dans le panier",
    pack_save:"Jusqu'à 10% de remise",
    based_on_reviews:"Basé sur 48 avis",
    // Contact
    contact_hero_tag:"✦ Nous sommes là pour vous",
    contact_hero_title:"Parlons-nous",
    contact_hero_sub:"Une question sur votre commande, les tailles, ou envie de dire bonjour ? Nous serions ravis de vous entendre.",
    stat_response:"Temps de réponse", stat_channels:"Canaux de contact", stat_cod_label:"Paiement à la livraison",
    reach_channels:"Nous contacter",
    channels_sub:"Nous sommes disponibles sur WhatsApp, Instagram et Facebook. Choisissez ce qui vous convient le mieux.",
    channel_wa_sub:"Chattez avec nous directement",
    channel_ig_sub:"Envoyez-nous un DM",
    channel_fb_sub:"Envoyez-nous un message",
    channel_response:"Nous répondons généralement sous 24 heures",
    form_sub:"Remplissez le formulaire et nous vous répondrons dès que possible.",
    first_name_label:"Prénom", last_name_label:"Nom", email_label:"Adresse e-mail",
    topic_label:"Sujet", topic_placeholder:"Sélectionner un sujet…",
    form_disclaimer:"Nous répondons sous 24h. Jamais de spam.",
    find_online:"Retrouvez-nous en ligne",
    prefer_chat:"Préférez-vous chatter ?",
    prefer_chat_sub:"WhatsApp est le moyen le plus rapide de nous joindre. Envoyez-nous un message et nous vous aiderons à trouver le jean parfait.",
    chat_whatsapp:"Chatter sur WhatsApp",
    browse_collection:"Voir la Collection →",
    msg_sent:"Message envoyé !",
    msg_sent_sub:"Merci de nous avoir contactés. Nous vous répondrons dans les 24 heures.",
    // FAQ
    faq_hero_tag:"✦ Centre d'aide",
    faq_hero_title:"Une question ? Nous avons les réponses.",
    faq_hero_sub:"Trouvez les réponses aux questions les plus fréquentes sur les commandes, les tailles, la livraison et plus.",
    faq_search_ph:"Rechercher une question…",
    faq_no_results:"Aucun résultat. Essayez un autre mot-clé ou contactez-nous.",
    faq_cat_all:"Toutes les questions", faq_cat_orders:"Commandes & Paiement",
    faq_cat_shipping:"Livraison", faq_cat_sizing:"Taille & Coupe", faq_cat_exchanges:"Échanges",
    still_help:"Besoin d'aide ?",
    still_help_sub:"Vous ne trouvez pas votre réponse ? Notre équipe répond en 24h — contactez-nous directement.",
    contact_us_arrow:"Nous contacter →",
    // Lookbook
    lookbook_series1:"Série Urbaine", lookbook_series2:"Édition Sombre",
    lookbook_series3:"Lavage Ciel", lookbook_grey:"L'Échelle des Gris",
    // About
    about_hero_sub:"NOUS SOMMES STREETSTORE",
    about_story_p:"StreetStore est né d'une passion pour la mode denim premium. Basé au Maroc, nous vous proposons le meilleur du denim féminin — des classiques jambe large aux coupes baggy modernes — à des prix accessibles. Chaque pièce est soigneusement sélectionnée pour sa qualité, son confort et son style.",
    val1_title:"Qualité Premium", val1_desc:"Nous utilisons uniquement les meilleurs tissus denim, issus de filières certifiées. Chaque paire passe par plus de 40 contrôles qualité avant de vous parvenir.",
    val2_title:"Durable", val2_desc:"Notre processus de production utilise 50% moins d'eau que la norme du secteur. Les emballages sont entièrement recyclables. Nous compensons 100% de nos émissions carbone.",
    val3_title:"Tailles Inclusives", val3_desc:"Le denim de qualité est fait pour tous les corps. Nous proposons des tailles XS à XXL et élargissons continuellement notre gamme en fonction des retours clients.",
    team_title:"Rencontrez l'équipe", team_section:"L'équipe",
    role1:"Fondatrice & Directrice Créative", role2:"Responsable Design", role3:"Responsable Développement Durable",
    cta_sub:"Denim premium pour la femme moderne. Explorez 12 styles signature, conçus pour durer.",
    // Contact stat
    stat_based:"Basé au Maroc",
    // FAQ stats & extra
    faq_stat_questions:"Questions répondues", faq_stat_categories:"Catégories",
    still_here:"Nous sommes toujours là.",
    faq_grp_shipping:"Livraison & Expédition", faq_grp_exchanges:"Échanges & Politique",
    // About
    about_est:"Fondé au Maroc",
    // Lookbook
    lookbook_title:"LE LOOKBOOK",
    // Shipping page
    sp_eyebrow:"✦ Nos politiques",
    sp_hero_sub:"Clair, simple et honnête — tout ce que vous devez savoir avant et après votre commande.",
    sp_stat1_val:"Gratuit", sp_stat1_label:"Livraison",
    sp_stat2_label:"Délai d'échange", sp_stat3_label:"Frais d'échange",
    sp_important:"Important — Veuillez lire avant de commander",
    sp_final_sale:"Vente finale",
    sp_pill1:"✗ Aucun remboursement", sp_pill2:"✗ Aucun retour", sp_pill3:"✓ Échange de taille uniquement",
    sp_card1_label:"Livraison standard", sp_card1_val:"Gratuit",
    sp_card1_note:"Toutes les commandes au Maroc. Livraison en 2 à 5 jours ouvrables.",
    sp_card2_label:"Livraison express",
    sp_card2_note:"Expédition prioritaire. Livraison en 1 à 2 jours ouvrables.",
    sp_card3_label:"Traitement de commande",
    sp_card3_note:"Les commandes avant 15h sont traitées le jour même.",
    sp_fee_tag:"Frais d'échange", sp_fee_h3:"Frais de réexpédition applicables",
    sp_step1_h4:"Contactez-nous",
    sp_step1_p:"Écrivez-nous sur WhatsApp ou via le formulaire de contact dans les 3 jours ouvrables suivant la livraison.",
    sp_step2_h4:"Envoyez une photo",
    sp_step2_p:"Photo de l'article — non porté, étiquettes attachées — pour confirmer l'éligibilité.",
    sp_step3_h4:"Payez 35 MAD",
    sp_step3_p:"Payez les frais d'échange. Votre nouvelle taille est expédiée immédiatement après confirmation.",
    sp_step4_h4:"Rendez l'article",
    sp_step4_p:"Remettez l'article original à notre livreur lors de la livraison de votre nouvelle taille.",
    sp_cta_eyebrow:"Nous sommes là pour vous", sp_cta_h3:"Vous avez encore des questions ?",
    sp_cta_p:"Contactez notre équipe sur WhatsApp ou via la page contact — nous répondons rapidement.",
    sp_cta_wa:"Chatter sur WhatsApp", sp_cta_contact:"Nous contacter →",
    sp_breadcrumb:"Livraison & Échanges",
  },

};
