/* ============================================================
   STREETSTORE — Translations  (EN / FR / AR)
   ============================================================ */
const TRANSLATIONS = {
  en: {
    // Nav
    nav_shop:"Shop", nav_lookbook:"Lookbook", nav_about:"About",
    nav_contact:"Contact", nav_account:"Account",
    // Hero
    hero_tag:"New Collection — Spring 2025",
    hero_h1_1:"TIMELESS DENIM.", hero_h1_2:"MODERN FIT.",
    hero_sub:"Premium Moroccan denim fashion. Crafted for bold, modern women.",
    hero_shop:"Shop Now", hero_lookbook:"View Lookbook",
    // Benefits
    benefit_quality:"Best Quality Fabrics", benefit_quality_sub:"Durable, comfy, perfect for daily wear",
    benefit_delivery:"Fast Delivery",       benefit_delivery_sub:"Get your favorite jeans delivered quickly",
    benefit_price:"Affordable Prices",      benefit_price_sub:"Fashion that fits your budget",
    // Grid
    new_in:"New In", the_collection:"The Collection", view_all:"View All →",
    quick_add:"Quick Add", sale:"Sale", trending:"Trending",
    // Trending section
    trending_now:"Trending Now", trending_sub:"The looks everyone's talking about this season.", shop_trending:"Shop Trending",
    // Editorial
    editorial:"Editorial", dress_street:"Dress the Street.",
    // Instagram
    the_feed:"The Feed", follow_insta:"Follow on Instagram",
    // Newsletter
    newsletter_label:"Newsletter", be_first:"Be First to Know",
    newsletter_sub:"New drops, exclusive offers, and behind-the-scenes — straight to your inbox.",
    subscribe:"Subscribe", email_placeholder:"Your email address",
    // Product page
    product_color:"Color:", product_size:"Size:", select_size:"Select a size",
    product_qty:"Quantity", add_to_cart:"Add to Cart",
    add_to_wishlist:"♡ Add to Wishlist", size_guide:"Size Guide",
    free_shipping:"Free Shipping", easy_returns:"Easy Returns", secure_payment:"Secure Payment",
    product_details:"Product Details", fabric_care:"Fabric & Care",
    acc_shipping_returns:"Shipping & Returns",
    complete_look:"Complete the Look",
    customer_reviews:"Customer Reviews", reviews_count:"Based on 48 reviews",
    skip:"Skip ›", zoom_hint:"⊕ Zoom", sold_out_badge:"Sold Out",
    reviews_avg_label:"Based on 48 reviews",
    // Shop
    all_jeans:"All Jeans", filters:"Filters", clear_all:"Clear All",
    sort_by:"Sort By", sort_featured:"Featured",
    sort_price_asc:"Price: Low to High", sort_price_desc:"Price: High to Low", sort_newest:"Newest",
    filter_size:"Size", filter_color:"Color", filter_fit:"Fit", filter_price:"Price",
    fit_all:"All", fit_skinny:"Skinny", fit_wide:"Wide Leg", fit_straight:"Straight", fit_mom:"Mom",
    // Cart
    your_cart:"Your Cart", subtotal:"Subtotal",
    free_ship_note:"Free shipping on all orders",
    checkout_btn:"Checkout", continue_shopping:"Continue Shopping →",
    cart_empty:"Your cart is empty.", you_might_like:"You might also like",
    shop_now_btn:"Shop Now",
    // Checkout
    step_info:"Information", step_shipping:"Shipping", step_payment:"Payment",
    contact_info:"Contact Information", shipping_method:"Shipping Method", payment:"Payment",
    first_name:"First Name", last_name:"Last Name", email:"Email",
    address_label:"Address", city:"City", postal_code:"Postal Code", country:"Country",
    continue_to_shipping:"Continue to Shipping", continue_to_payment:"Continue to Payment",
    place_order:"Place Order →", back_btn:"← Back", return_to_cart:"← Return to cart",
    standard_shipping:"Standard Shipping", express_shipping:"Express Shipping",
    days_std:"5–7 business days", days_exp:"2–3 business days",
    cod_title:"Cash on Delivery",
    cod_desc:"You will pay in cash when your order arrives at your door. No card required.",
    cod_note1:"📦 Our delivery agent will contact you before arrival.",
    cod_note2:"✅ Please have the exact amount ready.",
    cod_note3:"🔒 Your order is 100% secure and guaranteed.",
    cod_note4:"🇲🇦 We deliver across Morocco.",
    order_summary:"Order Summary", shipping_label:"Shipping", total_label:"Total", free:"Free",
    promo_code:"Promo Code", apply:"Apply", promo_ph:"Enter code",
    // About
    our_story:"Our Story", born_street:"Born on the street. Built for you.",
    explore_collection:"Explore the Collection",
    what_we_stand:"What We Stand For", our_values:"Our Values",
    meet_team:"Meet the Team", browse_all:"Browse All Jeans",
    shop_collection_cta:"Shop the Collection",
    stat_customers:"Customers", stat_styles:"Styles", stat_quality:"Quality", stat_payment:"Payment",
    // Lookbook
    lookbook_subtitle:"Spring / Summer 2025",
    shop_the_look:"Shop the Look", ready_to_shop:"Ready to Shop?",
    lookbook_ready_sub:"Explore the full collection and find your perfect fit.",
    shop_all_jeans:"Shop All Jeans",
    // Contact
    reach_out:"Reach Out", get_in_touch:"Get in Touch",
    send_message_title:"Send a Message",
    subject_label:"Subject", message_label:"Message", send_message:"Send Message",
    message_ph:"Tell us how we can help...", select_topic:"Select a topic",
    topic_order:"Order Inquiry", topic_returns:"Returns & Exchanges",
    topic_size:"Size & Fit Help", topic_wholesale:"Wholesale & Collaboration",
    topic_press:"Press & Media", topic_other:"Other",
    find_us:"Find Us Online", we_respond:"We respond within 24 hours",
    based_morocco:"Based in Morocco — We deliver across Morocco",
    // Account
    my_orders:"My Orders", wishlist:"Wishlist", profile:"Profile",
    addresses_tab:"Addresses", logout:"Logout", member_since:"Member since 2024",
    track:"Track", reorder:"Reorder",
    status_processing:"Processing", status_shipped:"Shipped", status_delivered:"Delivered",
    order_num:"Order #", date_col:"Date", items_col:"Items",
    total_col:"Total", status_col:"Status", action_col:"Action",
    // Footer
    footer_desc:"Premium women's denim crafted for the streets and everywhere in between.",
    footer_shop:"Shop", footer_help:"Help", footer_follow:"Follow",
    footer_all_jeans:"All Jeans", footer_new:"New Arrivals", footer_sale:"Sale",
    footer_contact:"Contact Us", footer_size_guide:"Size Guide",
    footer_shipping:"Shipping & Returns", footer_faq:"FAQ",
    footer_account:"My Account", footer_track:"Track Order",
    footer_rights:"© 2025 StreetStore. All rights reserved.",
    privacy:"Privacy Policy", terms:"Terms", cookies:"Cookie Policy",
    // Breadcrumb
    home:"Home",
    // Thank you
    order_confirmed:"Order Confirmed!",
    track_order:"Track Your Order", continue_shopping_btn:"Continue Shopping",
  },

  fr: {
    nav_shop:"Boutique", nav_lookbook:"Lookbook", nav_about:"À propos",
    nav_contact:"Contact", nav_account:"Compte",
    hero_tag:"Nouvelle Collection — Printemps 2025",
    hero_h1_1:"DENIM INTEMPOREL.", hero_h1_2:"COUPE MODERNE.",
    hero_sub:"Mode denim marocaine premium. Conçue pour les femmes audacieuses et modernes.",
    hero_shop:"Acheter maintenant", hero_lookbook:"Voir le Lookbook",
    benefit_quality:"Meilleure Qualité", benefit_quality_sub:"Durable, confortable, parfait pour le quotidien",
    benefit_delivery:"Livraison Rapide",  benefit_delivery_sub:"Recevez votre jean préféré rapidement",
    benefit_price:"Prix Abordables",     benefit_price_sub:"La mode qui s'adapte à votre budget",
    new_in:"Nouveautés", the_collection:"La Collection", view_all:"Voir tout →",
    quick_add:"Ajouter", sale:"Soldes", trending:"Tendance",
    trending_now:"Tendance du moment", trending_sub:"Les looks dont tout le monde parle cette saison.", shop_trending:"Voir les tendances",
    editorial:"Éditorial", dress_street:"Habille la rue.",
    the_feed:"Notre feed", follow_insta:"Suivre sur Instagram",
    newsletter_label:"Newsletter", be_first:"Soyez la première informée",
    newsletter_sub:"Nouvelles collections, offres exclusives, et coulisses — dans votre boîte mail.",
    subscribe:"S'abonner", email_placeholder:"Votre adresse e-mail",
    product_color:"Couleur:", product_size:"Taille:", select_size:"Choisir une taille",
    product_qty:"Quantité", add_to_cart:"Ajouter au panier",
    add_to_wishlist:"♡ Ajouter aux favoris", size_guide:"Guide des tailles",
    free_shipping:"Livraison gratuite", easy_returns:"Retours faciles", secure_payment:"Paiement sécurisé",
    product_details:"Détails du produit", fabric_care:"Tissu & Entretien",
    acc_shipping_returns:"Livraison & Retours",
    complete_look:"Complétez le look",
    customer_reviews:"Avis clients", reviews_count:"Basé sur 48 avis",
    skip:"Passer ›", zoom_hint:"⊕ Zoom", sold_out_badge:"Épuisé",
    reviews_avg_label:"Basé sur 48 avis",
    all_jeans:"Tous les jeans", filters:"Filtres", clear_all:"Effacer tout",
    sort_by:"Trier par", sort_featured:"En vedette",
    sort_price_asc:"Prix croissant", sort_price_desc:"Prix décroissant", sort_newest:"Nouveautés",
    filter_size:"Taille", filter_color:"Couleur", filter_fit:"Coupe", filter_price:"Prix",
    fit_all:"Tout", fit_skinny:"Skinny", fit_wide:"Jambe large", fit_straight:"Droit", fit_mom:"Mom",
    your_cart:"Votre Panier", subtotal:"Sous-total",
    free_ship_note:"Livraison gratuite sur toutes les commandes",
    checkout_btn:"Commander", continue_shopping:"Continuer vos achats →",
    cart_empty:"Votre panier est vide.", you_might_like:"Vous aimerez aussi",
    shop_now_btn:"Acheter maintenant",
    step_info:"Information", step_shipping:"Livraison", step_payment:"Paiement",
    contact_info:"Informations de contact", shipping_method:"Mode de livraison", payment:"Paiement",
    first_name:"Prénom", last_name:"Nom", email:"E-mail",
    address_label:"Adresse", city:"Ville", postal_code:"Code postal", country:"Pays",
    continue_to_shipping:"Continuer vers la livraison", continue_to_payment:"Continuer vers le paiement",
    place_order:"Passer la commande →", back_btn:"← Retour", return_to_cart:"← Retour au panier",
    standard_shipping:"Livraison standard", express_shipping:"Livraison express",
    days_std:"5–7 jours ouvrables", days_exp:"2–3 jours ouvrables",
    cod_title:"Paiement à la livraison",
    cod_desc:"Vous payez en espèces à la réception de votre colis. Aucune carte requise.",
    cod_note1:"📦 Notre livreur vous contactera avant l'arrivée.",
    cod_note2:"✅ Veuillez avoir le montant exact.",
    cod_note3:"🔒 Votre commande est 100% sécurisée.",
    cod_note4:"🇲🇦 Nous livrons partout au Maroc.",
    order_summary:"Récapitulatif", shipping_label:"Livraison", total_label:"Total", free:"Gratuit",
    promo_code:"Code promo", apply:"Appliquer", promo_ph:"Entrer le code",
    our_story:"Notre Histoire", born_street:"Né dans la rue. Fait pour vous.",
    explore_collection:"Explorer la collection",
    what_we_stand:"Ce que nous défendons", our_values:"Nos Valeurs",
    meet_team:"Rencontrez l'équipe", browse_all:"Voir tous les jeans",
    shop_collection_cta:"Découvrir la Collection",
    stat_customers:"Clientes", stat_styles:"Styles", stat_quality:"Qualité", stat_payment:"Paiement",
    lookbook_subtitle:"Printemps / Été 2025",
    shop_the_look:"Acheter le look", ready_to_shop:"Prête à faire du shopping?",
    lookbook_ready_sub:"Explorez la collection complète et trouvez votre style parfait.",
    shop_all_jeans:"Voir tous les jeans",
    reach_out:"Contactez-nous", get_in_touch:"Prendre contact",
    send_message_title:"Envoyer un message",
    subject_label:"Sujet", message_label:"Message", send_message:"Envoyer",
    message_ph:"Comment pouvons-nous vous aider...", select_topic:"Sélectionner un sujet",
    topic_order:"Renseignement sur commande", topic_returns:"Retours & Échanges",
    topic_size:"Aide taille & coupe", topic_wholesale:"Vente en gros & Collaboration",
    topic_press:"Presse & Médias", topic_other:"Autre",
    find_us:"Retrouvez-nous en ligne", we_respond:"Nous répondons sous 24h",
    based_morocco:"Basé au Maroc — Nous livrons partout au Maroc",
    my_orders:"Mes commandes", wishlist:"Favoris", profile:"Profil",
    addresses_tab:"Adresses", logout:"Déconnexion", member_since:"Membre depuis 2024",
    track:"Suivre", reorder:"Recommander",
    status_processing:"En traitement", status_shipped:"Expédié", status_delivered:"Livré",
    order_num:"Commande #", date_col:"Date", items_col:"Articles",
    total_col:"Total", status_col:"Statut", action_col:"Action",
    footer_desc:"Denim féminin premium, conçu pour les rues et bien plus encore.",
    footer_shop:"Boutique", footer_help:"Aide", footer_follow:"Suivre",
    footer_all_jeans:"Tous les jeans", footer_new:"Nouveautés", footer_sale:"Soldes",
    footer_contact:"Nous contacter", footer_size_guide:"Guide des tailles",
    footer_shipping:"Livraison & Retours", footer_faq:"FAQ",
    footer_account:"Mon compte", footer_track:"Suivre ma commande",
    footer_rights:"© 2025 StreetStore. Tous droits réservés.",
    privacy:"Politique de confidentialité", terms:"Conditions", cookies:"Politique cookies",
    home:"Accueil",
    order_confirmed:"Commande confirmée!",
    track_order:"Suivre ma commande", continue_shopping_btn:"Continuer mes achats",
  },

  ar: {
    nav_shop:"المتجر", nav_lookbook:"الاستعراض", nav_about:"من نحن",
    nav_contact:"اتصل بنا", nav_account:"حسابي",
    hero_tag:"مجموعة جديدة — ربيع 2025",
    hero_h1_1:"جينز لا يُنسى.", hero_h1_2:"قصة عصرية.",
    hero_sub:"أزياء الدنيم المغربية الفاخرة. مصممة للمرأة الجريئة والعصرية.",
    hero_shop:"تسوق الآن", hero_lookbook:"عرض الاستعراض",
    benefit_quality:"أفضل جودة أقمشة", benefit_quality_sub:"متين، مريح، مثالي للارتداء اليومي",
    benefit_delivery:"توصيل سريع",       benefit_delivery_sub:"احصل على جينزك المفضل بسرعة",
    benefit_price:"أسعار معقولة",        benefit_price_sub:"أزياء تناسب ميزانيتك",
    new_in:"وصل حديثاً", the_collection:"المجموعة", view_all:"عرض الكل →",
    quick_add:"إضافة سريعة", sale:"تخفيض", trending:"رائج",
    trending_now:"الأكثر رواجاً", trending_sub:"الإطلالات التي يتحدث عنها الجميع هذا الموسم.", shop_trending:"تسوق الرائج",
    editorial:"إديتوريال", dress_street:"ألبسي الشارع.",
    the_feed:"فيدنا", follow_insta:"تابعنا على إنستغرام",
    newsletter_label:"النشرة البريدية", be_first:"كوني أول من يعلم",
    newsletter_sub:"مجموعات جديدة، عروض حصرية، وكواليس — مباشرة إلى بريدك.",
    subscribe:"اشترك", email_placeholder:"بريدك الإلكتروني",
    product_color:"اللون:", product_size:"المقاس:", select_size:"اختر مقاساً",
    product_qty:"الكمية", add_to_cart:"أضف إلى السلة",
    add_to_wishlist:"♡ أضف للمفضلة", size_guide:"دليل المقاسات",
    free_shipping:"شحن مجاني", easy_returns:"إرجاع سهل", secure_payment:"دفع آمن",
    product_details:"تفاصيل المنتج", fabric_care:"القماش والعناية",
    acc_shipping_returns:"الشحن والإرجاع",
    complete_look:"أكمل الإطلالة",
    customer_reviews:"آراء العملاء", reviews_count:"بناءً على 48 تقييم",
    skip:"تخطي ›", zoom_hint:"⊕ تكبير", sold_out_badge:"نفد المخزون",
    reviews_avg_label:"بناءً على 48 تقييم",
    all_jeans:"جميع الجينزات", filters:"الفلاتر", clear_all:"مسح الكل",
    sort_by:"ترتيب حسب", sort_featured:"المميز",
    sort_price_asc:"السعر: من الأقل", sort_price_desc:"السعر: من الأعلى", sort_newest:"الأحدث",
    filter_size:"المقاس", filter_color:"اللون", filter_fit:"القصة", filter_price:"السعر",
    fit_all:"الكل", fit_skinny:"ضيق", fit_wide:"ساق واسعة", fit_straight:"مستقيم", fit_mom:"ماما",
    your_cart:"سلتك", subtotal:"المجموع الفرعي",
    free_ship_note:"شحن مجاني على جميع الطلبات",
    checkout_btn:"إتمام الطلب", continue_shopping:"متابعة التسوق →",
    cart_empty:"سلتك فارغة.", you_might_like:"قد يعجبك أيضاً",
    shop_now_btn:"تسوق الآن",
    step_info:"المعلومات", step_shipping:"الشحن", step_payment:"الدفع",
    contact_info:"معلومات التواصل", shipping_method:"طريقة الشحن", payment:"الدفع",
    first_name:"الاسم الأول", last_name:"الاسم الأخير", email:"البريد الإلكتروني",
    address_label:"العنوان", city:"المدينة", postal_code:"الرمز البريدي", country:"البلد",
    continue_to_shipping:"المتابعة إلى الشحن", continue_to_payment:"المتابعة إلى الدفع",
    place_order:"تأكيد الطلب ←", back_btn:"رجوع →", return_to_cart:"العودة إلى السلة →",
    standard_shipping:"شحن عادي", express_shipping:"شحن سريع",
    days_std:"5–7 أيام عمل", days_exp:"2–3 أيام عمل",
    cod_title:"الدفع عند الاستلام",
    cod_desc:"ستدفع نقداً عند وصول طلبك إلى بابك. لا بطاقة مطلوبة.",
    cod_note1:"📦 سيتصل بك مندوب التوصيل قبل الوصول.",
    cod_note2:"✅ يرجى تجهيز المبلغ بالضبط.",
    cod_note3:"🔒 طلبك مضمون 100%.",
    cod_note4:"🇲🇦 نوصل في جميع أنحاء المغرب.",
    order_summary:"ملخص الطلب", shipping_label:"الشحن", total_label:"الإجمالي", free:"مجاني",
    promo_code:"كود الخصم", apply:"تطبيق", promo_ph:"أدخل الكود",
    our_story:"قصتنا", born_street:"وُلد في الشارع. صُنع من أجلك.",
    explore_collection:"استكشف المجموعة",
    what_we_stand:"ما نؤمن به", our_values:"قيمنا",
    meet_team:"تعرف على الفريق", browse_all:"تصفح جميع الجينزات",
    shop_collection_cta:"تسوق المجموعة",
    stat_customers:"عميلة", stat_styles:"أنماط", stat_quality:"جودة", stat_payment:"الدفع",
    lookbook_subtitle:"ربيع / صيف 2025",
    shop_the_look:"تسوق الإطلالة", ready_to_shop:"مستعدة للتسوق؟",
    lookbook_ready_sub:"استكشفي المجموعة الكاملة وجدي قصتك المثالية.",
    shop_all_jeans:"تسوق جميع الجينزات",
    reach_out:"تواصل", get_in_touch:"تواصل معنا",
    send_message_title:"أرسل رسالة",
    subject_label:"الموضوع", message_label:"الرسالة", send_message:"إرسال",
    message_ph:"أخبرنا كيف يمكننا مساعدتك...", select_topic:"اختر موضوعاً",
    topic_order:"استفسار عن طلب", topic_returns:"الإرجاع والاستبدال",
    topic_size:"مساعدة في المقاسات", topic_wholesale:"البيع بالجملة والتعاون",
    topic_press:"الإعلام والصحافة", topic_other:"أخرى",
    find_us:"ابحثي عنا على الإنترنت", we_respond:"نرد في غضون 24 ساعة",
    based_morocco:"مقرنا في المغرب — نوصل في جميع أنحاء المغرب",
    my_orders:"طلباتي", wishlist:"المفضلة", profile:"الملف الشخصي",
    addresses_tab:"العناوين", logout:"تسجيل الخروج", member_since:"عضو منذ 2024",
    track:"تتبع", reorder:"إعادة الطلب",
    status_processing:"قيد المعالجة", status_shipped:"تم الشحن", status_delivered:"تم التسليم",
    order_num:"الطلب #", date_col:"التاريخ", items_col:"المنتجات",
    total_col:"الإجمالي", status_col:"الحالة", action_col:"الإجراء",
    footer_desc:"دنيم نسائي فاخر مصنوع للشوارع وما هو أبعد منها.",
    footer_shop:"المتجر", footer_help:"المساعدة", footer_follow:"تابعنا",
    footer_all_jeans:"جميع الجينزات", footer_new:"وصل حديثاً", footer_sale:"التخفيضات",
    footer_contact:"اتصل بنا", footer_size_guide:"دليل المقاسات",
    footer_shipping:"الشحن والإرجاع", footer_faq:"الأسئلة الشائعة",
    footer_account:"حسابي", footer_track:"تتبع طلبي",
    footer_rights:"© 2025 StreetStore. جميع الحقوق محفوظة.",
    privacy:"سياسة الخصوصية", terms:"الشروط والأحكام", cookies:"سياسة الكوكيز",
    home:"الرئيسية",
    order_confirmed:"تم تأكيد الطلب!",
    track_order:"تتبع طلبي", continue_shopping_btn:"متابعة التسوق",
  }
};
