services:
  - type: web
    name: streetstore-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: API_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: WEBSITE_URL
        value: https://lenovo452718.github.io
      - key: CLOUDINARY_URL
        sync: false

  - type: web
    name: streetstore-admin
    env: node
    rootDir: admin
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        value: https://streetstore-api.onrender.com
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://streetstore-api.onrender.com
