services:
  - type: web
    name: streetstore-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: mysql://u177512110_Noureddine:Ilovetowork53%21@srv2123.hstgr.io:3306/u177512110_Streetstore?connection_limit=5&pool_timeout=10
      - key: WEBSITE_URL
        value: https://streetstore.ma
      - key: JWT_SECRET
        sync: false
      - key: API_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
